### ISSUE TITLE
Program do not open

### ISSUE THREAD

**Issue by GabrieleGiacomelli** [jamesthejellyfish/isaac-save-edit-script#4]
Hi, good morning
I've encounter a problem with the program, i download it an hour ago and i try all things to get it work, but it just won't start. I have python and visual studio but i dosen't seem to do anything, the save file is on the same folder but still nothing, what can i do?

https://github.com/jamesthejellyfish/isaac-save-edit-script/assets/56293277/1d08d222-53bd-4c46-8401-022bf47d9cdd

**Comment by jamesthejellyfish** [comment]
hmm. It seems to work on all the computers I tested it on. I know windows sometimes marks it as unsafe so you may be having an issue with getting it to run because windows is keeping it from running. Try running it as an administrator, and if that doesn't work, download the latest source code (not the source from the releases page), install the dependencies listed in the "manual configuration section" of the readme, and then run "python gui.py" to run the GUI in python instead of the executable. That should hopefully give you more luck.

**Comment by jamesthejellyfish** [comment]
I've also just updated the source code in the release so you can re-download that as well.

**Comment by GabrieleGiacomelli** [comment]
i've tried the new download but still not working, i'll try with manual but i'm not so good with Python or code editing in general

**Comment by jamesthejellyfish** [comment]
In the source code folder, if you open a terminal (type "cmd" in the file bar at the top) at that folder and enter:
```bash
pip install tkinter
pip install ttkwidgets
python gui.py
```
Does it not work in that case?

**Comment by GabrieleGiacomelli** [comment]
it give me this error when trying pip install tkinter 
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

**Comment by GabrieleGiacomelli** [comment]
And this when try python guy.py dunno if its related 
`PS D:\Downloads\isaac-save-edit-script-main\isaac-save-edit-script-main> python gui.py
Traceback (most recent call last):
  File "gui.py", line 16, in <module>
    import gui_support
  File "D:\Downloads\isaac-save-edit-script-main\isaac-save-edit-script-main\gui_support.py", line 80
    match str(checkbox):
          ^
SyntaxError: invalid syntax`

**Comment by jamesthejellyfish** [comment]
Oh sorry. Try
```
pip install tk
```
Also what version of Python are you running? (Python --version)

**Comment by jamesthejellyfish** [comment]
Hmm. Then tkinter should be enabled in Python by default. Did ttkwidgets install correctly?

**Comment by GabrieleGiacomelli** [comment]
i did 
![image](https://github.com/jamesthejellyfish/isaac-save-edit-script/assets/56293277/d90bdea3-3a03-4e8e-853f-c1e09a8372d0)

**Comment by GabrieleGiacomelli** [comment]
if you have a moment if you don't wont to cointinue the conversation here we could go to discord, it would be much faster

**Comment by jamesthejellyfish** [comment]
I'm at work at the moment so I don't have access to discord. I'm also not totally sure why the script is not working for you, since match cases should be supported on your version of python, and I just did a clean install on a different machine and both the binary and the python script ran fine for me. You can try this altered version of the script which replaces the match case with else statements instead, but beyond that I am sort of at a loss.
[gui_support_no_match_case.zip](https://github.com/jamesthejellyfish/isaac-save-edit-script/files/14268864/gui_support_no_match_case.zip)

**Comment by GabrieleGiacomelli** [comment]
Oh yes it worked, thank you for your time and sorry if i bother you

**Comment by omfgnuts** [comment]
> if you have a moment if you don't wont to cointinue the conversation here we could go to discord, it would be much faster

it's not a good practice to do so. other people might have similar problems and there won't be a visibile solution for them, if you fixed it in the private dialogue.

on a side note, @jamesthejellyfish thank you so much for your work! I've been looking for the save edior just 2 days ago, to fix incorrect completion mark, but did it using repentogon! will use yours if anything else happens!
